title: Your Name
email: your.email@example.com
description: A brief description about yourself
url: "https://username.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Social links
github_username: username